### ISSUE TITLE
Menu dropdown

### ISSUE THREAD

**Issue by hopfrogsalerno** [tonystar/drupal-tweme#17]
In the new version7.3.0 the depth of the menu stops to 1

**Comment by tonystar** [comment]
This is not related to Tweme... Unfortunately multi-level dropdown menus have been removed in Bootstrap 3 :(

See these discussions for the details:
https://github.com/twbs/bootstrap/issues/160
http://stackoverflow.com/questions/9758587/twitter-bootstrap-multilevel-dropdown-menu
http://stackoverflow.com/questions/18023493/bootstrap-3-dropdown-sub-menu-missing

**Comment by hopfrogsalerno** [comment]
OK Thanks

Il 02/06/2015 23:58, Anton Staroverov ha scritto:
