### ISSUE TITLE
Site layout breaks theme completely by uploading a new logo on a fresh install.

### ISSUE THREAD

**Issue by DiviNe187** [tonystar/drupal-tweme#22]
Hi there,
Like we discussed on the Discuss forum:

To reproduce:
-Install the sandbox.
--Don't change anything.
---Go to Appearance--> Disable default logo --> Choose custom logo --> Save

Go back to the home page and it will be grey and the page/layout will be broken.

It seems to NOT be reversable, not even when removing the theme files and reinstall the theme, so basicly the site is, to say it neatly, *screwed*

So this error is very core related and has a high priority because i can imagine people that have had their site set up completely before installing Tweme to find their site broken with Tweme after to not be so amused.

Thanks in advance.

**Comment by tonystar** [comment]
Fixed in 7.x-3.0-beta1.

The issue was in Bootstrap base theme which does not support Bootstrap after v3.0.2. Tweme uses v3.3.4, that's why changing theme settings lead to the site broken.
