### ISSUE TITLE
H1, H2 and H3 tags disabling hyperlinks

### ISSUE THREAD

**Issue by mikedzl** [tonystar/drupal-tweme#28]
I know this sounds crazy but it appears that the theme is somehow disabling the hyperlink functionality in body content that is wrapped in H1, H2 and H3 tags. 

H4 and H5 tags allow links as does block level H1, H2 and H3 tags.

Switching the theme in Drupal from Tweme allows the hyperlink in the tags to work in the body content.

**Comment by mikedzl** [comment]
Got it figured out - it was the CSS in style.css (line 91 of style.less) copied below. 
If this was intentional then that's a pretty clever trick to force links to not work. ;-)

.region-content h1,
.region-content h2,
.region-content h3 {
  margin-top: -7rem;
  padding-top: 8rem;
  position: relative;
  z-index: -1;
}

Great work on this theme BTW!

**Comment by tonystar** [comment]
Your truth. This is because of negative z-index. Solution is to make positive value for elements inside headings. I'll try to fix it today or tomorrow!

**Comment by tonystar** [comment]
Hmm. The issue is not that simple! It takes more time than I expected.

By the way good joke J

**Comment by mikedzl** [comment]
Removing all of that code resolved the issue for me. I had however modified the page.tpl.php to move the <?php print $title ?> from the top jumbotron area to above the content as well as <?php print $breadcrumb ?>.

I've seen things overlap and break links before however so you may still be experiencing that in the jumbotron area with those two items.

Best of luck, the theme is awesome and helped me greatly in speeding up the development of a site I am working on. I will be sure to shoot you a note on Twitter when it's launched so you can see what I've built off your awesome base with Tweme. :)

**Comment by mikedzl** [comment]
Below is my modified page.tpl,php template which no longer has the problem for reference and quick drop in checking for you ;-)

----

<?php print render($page['body_top']) ?>

<div class="<?php print $navbar_classes ?>">
  <div class="container">
    <div class="navbar-header">
      <?php if (!empty($logo) || !empty($site_name)): ?>
      <a class="navbar-brand" href="<?php print $front_page ?>" title="<?php print t('Home') ?>">
        <?php if (!empty($logo)): ?>
        <img src="<?php print $logo ?>" alt="<?php print t('Home') ?>" />
        <?php endif ?>
        <?php if (!empty($site_name)): ?>
        <span><?php print $site_name ?></span>
        <?php endif ?>
      </a>
      <?php endif ?>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <?php if (!empty($primary_nav) || !empty($secondary_nav) || !empty($page['navigation'])): ?>
      <div class="navbar-collapse collapse">
        <nav role="navigation">
          <?php print render($primary_nav) ?>
          <?php print render($secondary_nav) ?>
          <?php print render($page['navigation']) ?>
        </nav>
      </div>
    <?php endif ?>
  </div>
</div>

<header class="header">
  <div class="jumbotron">
    <div class="container">
      <?php print render($page['header']) ?>
    </div>
  </div>
  <div class="header-bottom">
    <div class="container">
      <?php if (!empty($action_links)): ?>
      <ul class="action-links pull-right">
        <?php print render($action_links) ?>
      </ul>
      <?php endif ?>
      <?php print render($tabs) ?>
    </div>
  </div>
</header>

<section class="main">
  <div class="container">
    <div class="row">
      <?php $_content_cols = 12 - 3 * !empty($page['sidebar_first']) - 3 * !empty($page['sidebar_second']) ?>
      <section class="main-col col-md-<?php print $_content_cols  ?><?php print !empty($page['sidebar_first']) ? ' col-md-push-3' : '' ?>">
        <?php print $messages ?>
        <?php print render($page['help']) ?>
        <?php print render($page['highlighted']) ?>
		      <?php print $breadcrumb ?>
		<?php print render($title_prefix) ?>
      <h2><?php<?php print $title ?> ?></h2>
      <?php print render($title_suffix) ?>
        <?php print render($page['content']) ?>
      </section>
      <?php if (!empty($page['sidebar_first'])): ?>
      <aside class="main-col col-md-3 col-md-pull-<?php print $_content_cols  ?>">
        <?php print render($page['sidebar_first']) ?>
      </aside>
      <?php endif ?>
      <?php if (!empty($page['sidebar_second'])): ?>
      <aside class="main-col col-md-3">
        <?php print render($page['sidebar_second']) ?>
      </aside>
      <?php endif ?>
    </div>
  </div>
</section>

<?php print render($page['share']) ?>

<?php if ($page['bottom']): ?>
<section class="bottom">
  <div class="container">
    <?php print render($page['bottom']) ?>
  </div>
</section>
<?php endif ?>

<footer class="footer">
  <div class="container">
    <?php print render($page['footer']) ?>
  </div>
</footer>

<?php print render($page['body_bottom']) ?>

----

**Comment by tonystar** [comment]
Fixed in 7.x-3.0-beta2!
