### ISSUE TITLE
Chrome’s body rem font-size bug

### ISSUE THREAD

**Issue by ahughes3** [tonystar/drupal-tweme#33]
I have tweme installed. The font in my menu shows up extremely large like I've zoomed in on the browser but its set to 100%, if I zoom out then go back to 100% it is fine. Any thoughts?

![screen shot 2015-07-29 at 11 37 36 am](https://cloud.githubusercontent.com/assets/669850/8964525/b051ad16-35eb-11e5-9d87-d82cd11cf95e.png)
![screen shot 2015-07-29 at 11 39 24 am](https://cloud.githubusercontent.com/assets/669850/8964526/b05259fa-35eb-11e5-8557-015ece3c3b11.png)

**Comment by tonystar** [comment]
Just to reference: http://fvsch.com/code/bugs/chrome-rem-fontsize/
