### ISSUE TITLE
Notice: Uninitialized string offset: 0

### ISSUE THREAD

**Issue by GDI123** [tonystar/drupal-tweme#4]
I've got an error "Notice: Uninitialized string offset: 0 в функции tweme_navbar_menu_link() (строка 80 в файле \includes\theme.inc)."

there is a code
>if ($title[0] == '#') {

seems like this is wrong condition because $title is a UTF-8 string and can contain multibyte symbols if, for example, we will write title in Russian.
Solution can be to use drupal_substring() function
>if (drupal_substr($title, 0, 1) == '#') {

**Comment by tonystar** [comment]
Good point. I should definitely rework this line of code.

Could you provide an example of menu title causing such issue? I tested with Russian and it was ok.

**Comment by GDI123** [comment]
Maybe this is not fully correspond to the Tweme.
I've worked with panels and created a panel-page with selected option 'Settings->Menu->Normal Menu entry', but I left empty a title for menu. After that if I go to the other node-page or panel-page I'll see the error. Thus it seems like primary issue is in 'panels' module, because they allow to leave empty a menu title.

**Comment by tonystar** [comment]
Yes, this was caused by empty menu titles.

Checkout Tweme 3.x. It should work well.
