### ISSUE TITLE
what is the Header background block region and how to use it...

### ISSUE THREAD

**Issue by vinceyoumans** [tonystar/drupal-tweme#41]
I can use the Header region, but I was trying to use the background Header file... like a picture that would span then entire region of the header...   So I created some blocks, but I am not having much luck getting it to display...   can I get some assistance on how this is done please.
vince

**Comment by maxengel** [comment]
This helped me if you need a generic header background for specific pages, but doesn't address wanting custom ones that can be determined via a field: https://www.drupal.org/project/imageblock

**Comment by tonystar** [comment]
@maxengel thanks for pointing
@vinceyoumans further details is here: https://tweme.tonystar.me/#features
