### ISSUE TITLE
Host Tweme on the community owned Drupal.org?

### ISSUE THREAD

**Issue by Francewhoa** [tonystar/drupal-tweme#43]
Hi there project maintainer(s) :)

Our team is currently evaluating the possibility of making a large investment in time and energy into Tweme. Mostly in form of free contributions, such as suggested patches, documentation. And also sponsorships without strings attached.

But the main blocker we're facing is that Tweme project, documentation, and issues/tickets are currently hosted on Github :(

As you know Github is owned by a Corporation. Compare to Drupal.org which is owned by you the community users and the not-for-profit Drupal Association (DA). The DA first priority is to serve you the users. Drupal.org is not owned by a Corporation. So no interference from Corporations. Corporations are really welcome but as contributors. Not owner.

More benefits of hosting your project on drupal.org at https://www.drupal.org/node/648898

Have you considered hosting your project on drupal.org?

Cheers,

Francewhoa

![community_owned-corporation_owned-comparison-v02](https://cloud.githubusercontent.com/assets/119942/11230137/ea82e9c0-8d50-11e5-8de7-0c7e473147e7.png)

**Comment by Francewhoa** [comment]
Hi all open source enthusiasts :) If you're reading this and you're not familiar with community owned tools version corporate owned tools. Then you might be interested in the following.

The following is the details version of what I mean by "community owned" versus "corporation owned" tools

In the following I'll use GitHub as an example of a Corporate owned tool. Github is owned by a Corporation. Compare to Drupal.org which is owned by you the community users and the not-for-profit Drupal Association (DA). The DA first priority is to serve you the users. Drupal.org is not owned by a Corporation. So no interference from Corporations. Corporations are really welcome but as contributors. Not owner.

Drupal.org forums first priority is to **serve you the users**. Github first priority is to **serve their shareholders by hoarding money for them**.

I suggest to Drupal users to consider using community **owned** tools instead of corporate **owned** tools. Because the first priority of community **owned** tools is to serve you the users ;)
- - -

Here are some benefits of community **owned** versus corporation **owned**

An increasing number of people realized that the Drupal community first priority is to serve you and all its users. Compare to Corporations, where their first priority is to serve their stakeholders. Corporations do so by hoarding money for their stakeholders. Yes serving the Community is often on a Corporation list of priorities but it's a much lower priority ;)

For example, when a Corporation is facing a challenging decision and have to choose an higher priority between:
• Option 1: Increase their profit/Hoard more money; 
• Option 2: Serve the interest of the Community. 

Then most Corporations will not hesitate to go with option 1. Hoarding money. One real practical example is tomorrow morning you could receive an announcement from Github saying that for now on you have to pay them money to access part of their services. Or announcing that they will provide part of your private information to third parties to increase their money hoarding. Or announcing that they will close their website because their stakeholders are unhappy with the amount of money hoarding. With a Community **owned** project you're protected against such behaviors.

As you know Corporations are really welcome in the Drupal community but as contributors. Not **owner**. 

Corporations are not able to compete with the value of Community **owned** projects. Instead, they get value by both contributing to the Community **owned** project, and hoarding money via other channels. Conditional to not interfere with the Community decision making.

One clever action early taken by Dries, the founder of Drupal, was as early as 2001, to make the Drupal project Community **owned**. While at the same time welcoming contributions from anyone, including Corporations.

Sometime a website seem to be community **owned** because it uses wording such as "Creative Commons Attribution-ShareAlike (CC BY-SA)" or "Open Source". But if you search who owns that website you will find that it is **owned** by a corporation. Not **owned** by a community. 

Here is the source that demonstrate that Github is **owned** by the corporation "GitHub, Inc." at https://en.wikipedia.org/wiki/GitHub

Source about DA being owned by a not-for-profit organization at https://assoc.drupal.org/about

**Comment by tonystar** [comment]
Why not? Let's try!

It's better to manage the code here, on GitHub, but I agree with you — we should be a part of community. Because otherwise there is no community at all ;)

I've opened issue queues back on Drupal.org: https://www.drupal.org/project/tweme. You are welcome to migrate issues and to create documentation pages on Drupal.org!

**Comment by Francewhoa** [comment]
Thanks tonystar :)
