### ISSUE TITLE
Image don't show on header_background region

### ISSUE THREAD

**Issue by brainhell** [tonystar/drupal-tweme#46]
hi tony!!!! I'm trying to put an image in header_background region, but nothing occurs.....
I've created a block named "gdo-bg-img" and put it in header_background region.
Any idea?????

**Comment by maxengel** [comment]
I'm dealing with the same issue. I successfully did it by installing the "Image Block" plugin, creating an image block, and then moving it to the appropriate region (header background).

However, that works for things like a homepage, but I want it to be customizable on content pages. I tried following this guide: https://swsblog.stanford.edu/blog/using-display-suite-place-node-fields-blocks, but it doesn't seem to work with Tweme.

**Comment by tonystar** [comment]
@maxengel thanks for pointing
@vinceyoumans further details is here: https://tweme.tonystar.me/#features

@maxengel there is a better and simplier way. Let's create a feature request and I will do!
