### ISSUE TITLE
How do I configure the image for the Jumbotron

### ISSUE THREAD

**Issue by maxengel** [tonystar/drupal-tweme#48]
How do I configure the Jumbotron/header image?

**Comment by tonystar** [comment]
In the latest Tweme there is a special **Header background** region:

1. Create an image block using [Image Block](https://www.drupal.org/project/imageblock) contrib module.
2. Place this block in the **Header background** region. The image uploaded in image block is used as a background.
3. You can have multiple image blocks and control these blocks as usual.
