### ISSUE TITLE
Why bootstrap panel react so?

### ISSUE THREAD

**Issue by stefanocardo** [tonystar/drupal-tweme#55]
Hi Tonystar,

as you can see here:
http://www.bassclarinetwork.com/vandoren-B50

If I use it on a mobile phone or on resolution 320x480 I see the panels under Image stacked each other. The only panel unstacked (separated) is the last one (More).

The Drupal Page is a panel with this structure:

![panel design](https://cloud.githubusercontent.com/assets/14326820/23066748/6f574270-f51c-11e6-8f00-cafd0a238cc2.png)

The stacked panels are all in the first row.

Thank you so much in advance!!

Stefano

**Comment by tonystar** [comment]
@stefanocardo what do you mean by "unstacked"? can you please attache a screenshot? thanks!

**Comment by stefanocardo** [comment]
Hi! You can see here http://www.bassclarinetwork.com/vandoren-B50

Redicing the size of the window of the browser 

Thank you!!!

**Comment by stefanocardo** [comment]
When you have something like a smartphone, the four regions which have a Boostrap Primary Panel appereance, results without a space between them.

**Comment by stefanocardo** [comment]
![panel problem](https://cloud.githubusercontent.com/assets/14326820/23079353/ddcb6954-f54c-11e6-86c2-8ccafcb221cf.png)

**Comment by tonystar** [comment]
This is because first 4 blocks are in the separate row, and in your setup each row has bottom padding:

```css
.panels-flexible-26 .panels-flexible-row {
    padding: 0 0 0.5em 0;
    margin: 0;
}
```

Closing the issue since it's not related to Tweme.
